# Generated by Django 5.0.7 on 2025-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
